### PR TITLE
Tests for Scheduler and other related packages (WIP...)

### PR DESCRIPTION
**Pull request by vladimirvivien**
PR to add tests for Scheduler and other related package (where possible). 
  * ~~Test pkg/proc~~ (@jdef did it)
  * [ ] Test pkg/scheduler/ha 
  * [ ] Test for pkg/scheduler/scheduler.go (if possible mocking may be tricky)
  * Will add more as needed

### CODE REVIEW

**Comment by jdef** [comment]
Looks like you're working off an old copy of master. I submitted some tests for the proc package with the merge of the constraints spec stuff.

**Comment by vladimirvivien** [comment]
@jdef OK.

**Comment by jdef** [comment]
Can we close this out and then start a new PR when you have changes ready to review? Also, are you rebasing instead of merging when pulling in changes from master? If not, please consider doing so because it makes the commit logs much easier to parse.

**Comment by vladimirvivien** [comment]
Closing this PR in favor of a cleaner to be proposed when ready for review.

**Pull request closed without merging**
