### PR TITLE
DCOS: Asset server and reverse proxy

### PR DESCRIPTION
**Pull request by tsenart**
/cc @sttts

### CODE REVIEW

**Comment by jdef** [comment]
something to consider: kubectl itself already provides reverse proxy capabilities. I believe that it also handles HTTP to SPDY connection upgrades, which are required for some apiserver endpoints.

have we already exhausted the possibility of using kubectl for proxying?

**Comment by sttts** [comment]
Do you have an idea how to use it for that? Afaik it can only proxy services to make them available on the local host.

**Comment by jdef** [comment]
looks like 127.0.0.1 is hardcoded. however, we could save ourselves some elbow grease and just embed the kubectl.ProxyServer in a struct of our own, and override the Listen() func.

building a ProxyServer looks pretty easy:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/proxy.go

and the Listen() func is pretty straightforward to override:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/proxy_server.go#L181

thoughts?

**Comment by sttts** [comment]
If the code is re-usable, I am all for it. @tsenart has to take a look.

**Comment by tsenart** [comment]
Remember that besides the proxy, we need to serve files too. But yeah, I don't want to write SPDY upgrade code if I don't have to... So, I'm +1 on reusing that code for the proxy function.

**Comment by tsenart** [comment]
I won't be able to work on this until next week, so feel free to take over if it's a priority.

**Comment by karlkfi** [comment]
@tsenart What's the status of this? Should it be upstream in contrib? I know there was work recently on a reverse proxy that was demoed at a recent k8s sync.

**Comment by sttts** [comment]
I would like to approach this topic again in the next sprint.

**Comment by sttts** [comment]
Superseeded by https://github.com/mesosphere/kubernetes-mesos/pull/519. Closing.

**Pull request closed without merging**
