### PR TITLE
sync arch diagram w/ current implementation, as of k8s v0.14 integration

### PR DESCRIPTION
**Pull request by jdef**
Updated diagrams, needed for related blueprint docs.

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
For the purposes of this diagram, I think we can drop the communication line between the slave process and dockerd.

**Comment by ConnorDoyle** [comment]
Could we add a line between Zookeeper and the K-M scheduler (for master detection?)

**Comment by ConnorDoyle** [comment]
When we do the next rebase we'll be able to pass the parent cgroup to the kubelet to make the executor container enclose the pods!

**Comment by ConnorDoyle** [comment]
Where does the scheduler talk directly to etcd?

**Comment by jdef** [comment]
scheduler stores frameworkID in etcd (pkg/scheduler/service). Also uses
etcd for ha leader election (pkg/election)

**Comment by jdef** [comment]
Yep, super excited about that!

I think it'll save time to just upstream what we have first (vs. a separate
rebase cycle), and as part of that effort we can have the executor
container enclose the pods. We're getting close to 1.0 upstream code freeze
and I want to have a working upstream PR in place by then.

**Comment by jdef** [comment]
@ConnorDoyle Thanks for the feedback, I've addressed your concerns. PTAL

**Comment by ConnorDoyle** [comment]
LGTM!  :ship: :ship: :ship:

**Pull request merged**
