### PR TITLE
Rebase to k8s v0.11.0

### LINKED ISSUE #152: zombie pods can accumulate because assignPods doesn't check for pod existence
xref https://github.com/GoogleCloudPlatform/kubernetes/issues/4757

### LINKED ISSUE #153: rebase to v0.11+
* want to pick up fix for #152
* want to pick up the many, many bug fixes in between 0.8 and 0.11
* update kubelet patches, prepare for PR's

### PR DESCRIPTION
**Pull request by jdef**
- fixes #152 
- fixes #153 
- [x] working simple examples
- [x] working guestbook examples
- [x] fix failing broken tests
- [x] burn-in testing
- [x] profiled

### CODE REVIEW

**Comment by aminjam** [comment]
+1 Looking forward to this merge.

**Comment by jdef** [comment]
slave died during burn-in testing. not sure why. cpu was at %100. disk utilization dropped to 0 about the same time the cpu was pegged, so I'm my first guess was that it ran out of disk space. my next guess was that some process freaked out (probably a k8s or k8sm process in a forever loop) and then spun indefinitely, consuming cycles. unfortunately i couldn't ssh into the node. I restarted the node and although GCE reports it started, I can't SSH into it.

However, I also observed (before the reboot) a kernel oops via GCE's console log for the VM, roughly around the time that the CPU spiked and the disk dropped:

```
[4341257.253050] BUG: unable to handle kernel NULL pointer dereference at 0000000000000078
[4341257.256009] IP: [<ffffffff810a4559>] check_preempt_wakeup+0xd9/0x1d0
[4341257.256009] PGD 601c6067 PUD 5348b067 PMD 0 
[4341257.256009] Oops: 0000 [#1] SMP 
[4341257.256009] Modules linked in: veth xt_nat xt_REDIRECT xt_addrtype xt_conntrack ipt_MASQUERADE iptable_nat nf_nat_ipv4 nf_nat bridge stp llc aufs(C) ip6table_filter ip6_tables xt_comment xt_tcpudp nf_conntrack_ipv4 nf_defrag_ipv4 xt_state nf_conntrack iptable_filter ip_tables x_tables crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw processor gf128mul glue_helper parport_pc parport evdev i2c_piix4 i2c_core thermal_sys pcspkr ablk_helper cryptd button ext4 crc16 mbcache jbd2 sg sd_mod crc_t10dif crct10dif_common virtio_scsi scsi_mod virtio_net crc32c_intel virtio_pci virtio_ring virtio
[4341257.256009] CPU: 1 PID: 16707 Comm: dockerinit-1.4. Tainted: G         C    3.16-0.bpo.2-amd64 #1 Debian 3.16.3-2~bpo70+1
[4341257.256009] Hardware name: Google Google, BIOS Google 01/01/2011
[4341257.256009] task: ffff88011d970110 ti: ffff88000dad4000 task.ti: ffff88000dad4000
[4341257.256009] RIP: 0010:[<ffffffff810a4559>]  [<ffffffff810a4559>] check_preempt_wakeup+0xd9/0x1d0
[4341257.256009] RSP: 0018:ffff88000dad7e30  EFLAGS: 00010002
[4341257.256009] RAX: 0000000000000000 RBX: ffff88021fd141c0 RCX: 0000000000000002
[4341257.256009] RDX: 0000000000000000 RSI: ffff88021529c350 RDI: ffff88021fd14238
[4341257.256009] RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000000
[4341257.256009] R10: ffffffffffffffe0 R11: 0000000000000000 R12: ffff8801c869d940
[4341257.256009] R13: ffff88011d970110 R14: 0000000000000000 R15: 0000000000000000
[4341257.256009] FS:  000000000322e880(0063) GS:ffff88021fd00000(0000) knlGS:0000000000000000
[4341257.256009] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[4341257.256009] CR2: 0000000000000078 CR3: 0000000083c4d000 CR4: 00000000000406e0
[4341257.256009] Stack:
[4341257.256009]  0000000000000000 ffffffff00000000 ffff88020000006e ffff88021fd141c0
[4341257.256009]  ffff88021529c9d4 0000000000000286 00000000000141c0 ffff88021fd141c0
[4341257.256009]  0000000000000002 ffffffff8109aca4 ffff88021529c350 ffffffff8109df54
[4341257.256009] Call Trace:
[4341257.256009]  [<ffffffff8109aca4>] ? check_preempt_curr+0x84/0xa0
[4341257.256009]  [<ffffffff8109df54>] ? wake_up_new_task+0xf4/0x1b0
[4341257.256009]  [<ffffffff811824cd>] ? mprotect_fixup+0x15d/0x250
[4341257.256009]  [<ffffffff8106b00f>] ? do_fork+0xcf/0x340
[4341257.256009]  [<ffffffff815467d9>] ? stub_clone+0x69/0x90
[4341257.256009]  [<ffffffff8154646d>] ? system_call_fast_compare_end+0x10/0x15
[4341257.256009] Code: 00 00 83 e8 01 4d 8b 64 24 70 39 d0 7f f4 48 8b 7d 78 49 3b 7c 24 78 74 1d 66 0f 1f 84 00 00 00 00 00 48 8b 6d 70 4d 8b 64 24 70 <48> 8b 7d 78 49 3b 7c 24 78 75 ec 48 85 ff 74 e7 e8 f2 f9 ff ff 
[4341257.256009] RIP  [<ffffffff810a4559>] check_preempt_wakeup+0xd9/0x1d0
[4341257.256009]  RSP <ffff88000dad7e30>
[4341257.256009] CR2: 0000000000000078
[4341257.256009] ---[ end trace 5bc72dbb40fd7c66 ]---
```

The current console shows that the node started, and some procs running (including SSH) but I still can't connect in. Probably going to have to kill this dev cluster and bring up a new one. Leaving the other slaves running for now, will check back later tonight. Would love to get at the logs on the dead node. Not sure how.

**Comment by jdef** [comment]
following up on the previously dead slave. it's running again and I can log in. from syslog:
```
Feb 25 22:18:49 development-3273-e3f mesos-slave[15849]: I0225 22:18:49.763727 15875 slave.cpp:2215] Handling status update TASK_STARTING (UUID: 45f99b56-bd3c-11e4-8b34-42010a4848b2) for task 24d4d21c-bd3c-11e4-8df7-42010adf71e3 of framework 20150221-134408-3815890698-5050-18127-0018 from executor(1)@10.72.72.178:37061
Feb 25 22:18:49 development-3273-e3f mesos-slave[15849]: I0225 22:18:49.764753 15875 status_update_manager.cpp:317] Received status update TASK_STARTING (UUID: 45f99b56-bd3c-11e4-8b34-42010a4848b2) for task 24d4d21c-bd3c-11e4-8df7-42010adf71e3 of framework 20150221-134408-3815890698-5050-18127-0018
Feb 25 22:18:49 development-3273-e3f mesos-slave[15849]: I0225 22:18:49.765347 15875 slave.cpp:2458] Forwarding the update TASK_STARTING (UUID: 45f99b56-bd3c-11e4-8b34-42010a4848b2) for task 24d4d21c-bd3c-11e4-8df7-42010adf71e3 of framework 20150221-134408-3815890698-5050-18127-0018 to master@10.223.113.227:5050
Feb 25 22:18:49 development-3273-e3f mesos-slave[15849]: I0225 22:18:49.765514 15875 slave.cpp:2391] Sending acknowledgement for status update TASK_STARTING (UUID: 45f99b56-bd3c-11e4-8b34-42010a4848b2) for task 24d4d21c-bd3c-11e4-8df7-42010adf71e3 of framework 20150221-134408-3815890698-5050-18127-0018 to executor(1)@10.72.72.178:37061
Feb 25 22:18:49 development-3273-e3f mesos-slave[15849]: I0225 22:18:49.771008 15872 status_update_manager.cpp:389] Received status update acknowledgement (UUID: 45f99b56-bd3c-11e4-8b34-42010a4848b2) for task 24d4d21c-bd3c-11e4-8df7-42010adf71e3 of framework 20150221-134408-3815890698-5050-18127-0018
--- (jdefelice) there are a bunch of zero-bytes here
Feb 25 23:22:36 development-3273-e3f kernel: imklog 5.8.11, log source = /proc/kmsg started.
Feb 25 23:22:36 development-3273-e3f rsyslogd: [origin software="rsyslogd" swVersion="5.8.11" x-pid="1776" x-info="http://www.rsyslog.com"] start
Feb 25 23:22:36 development-3273-e3f kernel: [    0.000000] Initializing cgroup subsys cpuset
Feb 25 23:22:36 development-3273-e3f kernel: [    0.000000] Initializing cgroup subsys cpu
Feb 25 23:22:36 development-3273-e3f kernel: [    0.000000] Initializing cgroup subsys cpuacct
Feb 25 23:22:36 development-3273-e3f kernel: [    0.000000] Linux version 3.16-0.bpo.2-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.16.3-2~bpo70+1 (2014-09-21)
Feb 25 23:22:36 development-3273-e3f kernel: [    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-3.16-0.bpo.2-amd64 root=UUID=87239a97-c5a4-4a87-b545-606ffbff926c ro console=ttyS0,38400n8 console=ttyS0
Feb 25 23:22:36 development-3273-e3f kernel: [    0.000000] Disabled fast string operations
Feb 25 23:22:36 development-3273-e3f kernel: [    0.000000] e820: BIOS-provided physical RAM map:
...
```
GCE CPU Utilization, at 22:17, had been very slowly increasing over the last couple of hours - then spiked to over 80% by 22:22. The slow increase is likely due to docker containers **no longer being garbage collected** for some reason. This consumption of CPU as the number of dead dockers increases is a known problem. The fact that the number of dead dockers is constantly increasing is a problem and suggests a problem with the kubelet's container garbage collection loop. The accumulation of dead containers is visible on other slaves in the cluster as well. This was not a problem prior to the v0.11.0 rebase.

**Comment by jdef** [comment]
xref https://github.com/GoogleCloudPlatform/kubernetes/issues/157

**Comment by jdef** [comment]
for posterity:
```shell
$ sudo docker --version
Docker version 1.4.1, build 5bc2ff8
$ dpkg -l | grep -e mesos
ii  mesos                                   0.21.0-1.0.debian77                                 amd64        Cluster resource manager with efficient resource isolation
$ uname -a
Linux development-3273-173 3.16-0.bpo.2-amd64 #1 SMP Debian 3.16.3-2~bpo70+1 (2014-09-21) x86_64 GNU/Linux
```

**Comment by jdef** [comment]
Problem is that there is no limit on the total number of dead containers, only the number of dead containers per pod.
https://github.com/GoogleCloudPlatform/kubernetes/tree/646621e0e88ce92b32057627c53af1447ccdda90/pkg/kubelet#L397

**Pull request merged**
